debug: true

build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/drone-kubernetes
  commands:
    - go get github.com/drone/drone-plugin-go/plugin
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo

notify:
  webhook:
    image: ipedrazas/drone-webhook
    urls:
      - http://deep-api.ipedrazas.k8s.co.uk:5000/webhooks
      - http://deep-api.ipedrazas.k8s.co.uk:5000/debug

publish:
  docker:
    registry: quay.io
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/drone-kubernetes
    tag:
      - latest
      - "$$BUILD_NUMBER"
    when:
      branch: master

    branch: master

